### ISSUE TITLE
I've been having troubles with the maven repository

### ISSUE THREAD

**Issue by jimmy9gag** [testobject/appium-java-example#1]
the url http://nexus.testobject.org/nexus/content/repositories/testobject-public-repo/ seem to show nothing. I keep failing to collect required dependencies.

Failed to collect dependencies at org.testobject.extras.appium:appium-java-api:jar:0.0.11: Failed to read artifact descriptor for org.testobject.extras.appium:appium-java-api:jar:0.0.11: Could not transfer artifact org.testobject.extras.appium:appium-java-api:pom:0.0.11 from/to testobjects-repository (http://nexus.testobject.org/nexus/content/repositories/testobject-public-repo/): Failed to transfer file: http://nexus.testobject.org/nexus/content/repositories/testobject-public-repo/org/testobject/extras/appium/appium-java-api/0.0.11/appium-java-api-0.0.11.pom. Return code is: 500

seems like the repo is empty..

**Comment by aluedeke** [comment]
just double checked:

http://nexus.testobject.org/nexus/content/repositories/testobject-public-repo/org/testobject/extras/appium/appium-java-api/0.0.11/appium-java-api-0.0.11.pom

is working for me. Can you please try that again.

**Comment by ragog** [comment]
Issue is solved, closing.
